spring:
 datasource:
url: jdbc:mysql://localhost:3306/easychat
username: root
password: beihuai
driver-class-name: com.mysql.cj.jdbc.Driver
profiles:
active: dev
jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
dialect: org.hibernate.dialect.MySQLDialect
format_sql: true

